
spring:
  application:
    name: scpi-inv-api
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.check-consulting.net/realms/scpi-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          audiences: account

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  auth:
    converter:
      ressource-id: scpi-invest-front
      principal-attribute: preferred_username

minio:
  url: "http://localhost:9000"
  access-key: admin
  secret-key: admin-admin

keycloak:
  auth-server-url: https://keycloak.check-consulting.net
  realm: scpi-realm
  resource: scpi-invest-front
  public-client: true
  credentials:
    secret: ""
  admin:
    username: admin
    password: admin

logging:
  level:
    org.flywaydb.core: INFO
