spring:
  application:
    name: scpi-inv-api
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

minio:
  url: "http://localhost:9000"
  access-key: admin
  secret-key: admin-admin

logging:
  level:
    org.flywaydb.core: INFO

