apiVersion: v1
kind: ConfigMap
metadata:
  name: scpi-inv-api-config
  labels:
    app: scpi-inv-api
data:
  APP_ENV: "{{ .Values.application.environment }}"
  DATABASE_URL: "{{ .Values.application.database.url }}"
  OAUTH2_ISSUER_URI: "{{ .Values.application.security.oauth2.issuer_uri }}"
  OAUTH2_RESOURCE_ID: "{{ .Values.application.security.oauth2.resource_id }}"
  OAUTH2_PRINCIPAL_ATTRIBUTE: "{{ .Values.application.security.oauth2.principal_attribute }}"
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.application.kafka.bootstrap_servers }}"
  MINIO_URL: "{{ .Values.application.minio.url }}"
  KEYCLOAK_SERVER_URL: "{{ .Values.application.keycloak.server_url }}"
  KEYCLOAK_REALM: "{{ .Values.application.keycloak.realm }}"
  SCPI_INV_NOTIFICATION_URL: "{{ .Values.application.scpi_inv_notification_url }}"
  SEND_EMAIL_PATH: "{{ .Values.application.send_email_path }}"
  FLYWAY_LOG_LEVEL: "{{ .Values.application.logging.level.flyway }}"
  KAFKA_LOG_LEVEL: "{{ .Values.application.logging.level.kafka }}"
  APP_LOG_LEVEL: "{{ .Values.application.logging.level.app }}"
