apiVersion: apps/v1
kind: Deployment
metadata:
  name: scpi-inv-api
  labels:
    app: scpi-inv-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scpi-inv-api
  template:
    metadata:
      name: scpi-inv-api
      labels:
        app: scpi-inv-api
    spec:
      containers:
        - name: scpi-inv-api
          image: "{{.Values.image.repo}}/{{.Values.image.name}}:{{.Values.image.tag}}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: scpi-inv-api-config
            - secretRef:
                name: app-secrets